import Head from "next/head";
import dynamic from "next/dynamic";
import { CardanoWallet, useWallet } from "@meshsdk/react";
import { useEffect, useState } from "react";
import Login from "@/components/login";
// import Navbar from "@/components/Navbar";

const RTC = dynamic(() => import("@/components/rtc"), {
  ssr: false,
});

export default function Home() {
  // const { connected } = useWallet();

  // useEffect(() => {
  //   async function load() {
  //     const usedAddresses = await wallet.getUsedAddresses();
  //     console.log("usedAddresses[0]", usedAddresses[0]);
  //     setUserId(usedAddresses[0]);
  //   }
  //   if (connected) {
  //     load();
  //   }
  // }, [connected]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* {!connected && <Login />}
        {connected && <RTC />} */}
        <RTC />
      </main>
    </>
  );
}
